spring:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    # testOnBorrow: true
    # validationQuery: SELECT 1 FROM DUAL
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000 # Default: 30000 (30 seconds)
      connection-test-query: SELECT 1
      minimum-idle: 50 # Default: same as maximumPoolSize
      maximum-pool-size: 500 # Default: 10

ignite:
  igniteInstanceName: properties-instance-name
  communicationSpi:
    localPort: 5555
  dataStorageConfiguration:
    defaultDataRegionConfiguration:
      initialSize: 10485760 #10MB
    dataRegionConfigurations:
      - name: my-dataregion
        initialSize: 104857600 #100MB
  cacheConfiguration:
    - name: accounts
      queryEntities:
        - tableName: ACCOUNTS
          keyFieldName: ID
          keyType: java.lang.Long
          valueType: java.lang.Object
          fields:
            ID: java.lang.Long
            amount: java.lang.Double
            updateDate: java.util.Date
    - name: my-cache2
    - name: test01
